# general setting
name: cuts
backend: dp # DataParallel
type: FMNetModel
num_gpu: auto
manual_seed: 2
non-isometric: True
partial: true

# path
path:
  resume_state: ~


# datasets
datasets:
  train_dataset:
    name: Shrec16Train
    type: PairShrec16geoDataset
    data_root: ./wormhole/SHREC16/SHREC16/
    cut_type: cuts
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: True
    return_mask: True
    is_train: True
    distance_folder: ./wormhole/SHREC16
  test_dataset:
    name: Shrec16Val
    type: PairShrec16geoDataset
    data_root: ./wormhole/SHREC16/SHREC16_test/
    cut_type: cuts
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: True
    return_dist: True
    return_mask: False
    is_train: False
    distance_folder: ./wormhole/SHREC16
  # setting for train dataset
  batch_size: 1
  num_worker: 8

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 3
    out_channels: 256
    cache_dir: ./wormhole/SHREC16/SHREC16/cuts/diffusion
    input_type: xyz
    use_normals: True
  permutation:
    type: Similarity
    tau: 0.01

# training setting
train:
  total_epochs: 300
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 300
  losses:
    geodesic_loss:
      type: PartialGeodesicLoss
      loss_weight: 1.0e+3
    surfmnet_loss:
      type: PartialOrthoLoss
      w_orth: 1.0


# validation setting
val:
  val_freq: 2000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 2000
